console.log("Hello world");
alert("Are you sure to use this page");
  
let box1=2;
let box2=6;
let box3=15;
console.log(box3);
console.log("box3");
let megha=100;
result1= megha + 10;
console.log(result1);
const number=68;
console.log(number);
let number1=10;
let number2=30;
console.log(number1+number2);
console.log(number1-number2);
console.log(number1*number2);
console.log(number1/number2);
console.log(number1%number2);
console.log(number1**number2);
console.log(number1==number2);
console.log(number1!=number2);
console.log(number1===number2);
console.log(number1<number2);
console.log(number1>number2);
console.log(number2!=60);
console.log(number1<=number2);
let a=45;
let b=70;
let result=(a+b)*number;
console.log(result);